package com.rnexamples.sparkstreaming

object StreamingSchemas {
  def schemaMatch(table: String): String = table match {
    case "airports" => "{\"namespace\": \"com.rnexamples\",\"type\": \"record\",\"name\": \"airport_record\",\"fields\":[{  \"name\": \"iata\", \"type\": \"string\"},{   \"name\": \"name\",  \"type\": \"string\"},{   \"name\": \"city\",  \"type\": \"string\"},{   \"name\": \"country\",  \"type\": \"string\"},{   \"name\": \"lat\",  \"type\": \"double\"},{   \"name\": \"long\",  \"type\": \"double\"}]}"
    case "carriers" => "{\"namespace\": \"com.rnexamples\",\"type\": \"record\",\"name\": \"carrier_record\",\"fields\":[{  \"name\": \"code\", \"type\": \"string\"},{   \"name\": \"description\",  \"type\": \"string\"}]}"
    case "planes"   => "{\"namespace\": \"com.rnexamples\",\"type\": \"record\",\"name\": \"plane_record\",\"fields\":[{  \"name\": \"tailnum\", \"type\": \"string\"},{  \"name\": \"type\", \"type\": \"string\"},{  \"name\": \"manufacturer\", \"type\": \"string\"},{  \"name\": \"issue_date\", \"type\": \"string\"},{  \"name\": \"model\", \"type\": \"string\"},{  \"name\": \"status\", \"type\": \"string\"},{  \"name\": \"aircraft_type\", \"type\": \"string\"},{  \"name\": \"engine_type\", \"type\": \"string\"},{  \"name\": \"year\", \"type\": \"string\"}]}"
    case "flights"  => "{\"namespace\": \"com.rnexamples\",\"type\": \"record\",\"name\": \"flight_record\",\"fields\":[{  \"name\": \"Year\", \"type\": \"string\"},{  \"name\": \"Month\", \"type\": \"string\"},{  \"name\": \"DayofMonth\", \"type\": \"string\"},{  \"name\": \"DayOfWeek\", \"type\": \"string\"},{  \"name\": \"DepTime\", \"type\": \"string\"},{  \"name\": \"CRSDepTime\", \"type\": \"string\"},{  \"name\": \"ArrTime\", \"type\": \"string\"},{  \"name\": \"CRSArrTime\", \"type\": \"string\"},{  \"name\": \"UniqueCarrier\", \"type\": \"string\"},{  \"name\": \"FlightNum\", \"type\": \"string\"},{  \"name\": \"TailNum\", \"type\": \"string\"},{  \"name\": \"ActualElapsedTime\", \"type\": \"string\"},{  \"name\": \"CRSElapsedTime\", \"type\": \"string\"},{  \"name\": \"AirTime\", \"type\": \"string\"},{  \"name\": \"ArrDelay\", \"type\": \"string\"},{  \"name\": \"DepDelay\", \"type\": \"string\"},{  \"name\": \"Origin\", \"type\": \"string\"},{  \"name\": \"Dest\", \"type\": \"string\"},{  \"name\": \"Distance\", \"type\": \"string\"},{  \"name\": \"TaxiIn\", \"type\": \"string\"},{  \"name\": \"TaxiOut\", \"type\": \"string\"},{  \"name\": \"Cancelled\", \"type\": \"string\"},{  \"name\": \"CancellationCode\", \"type\": \"string\"},{  \"name\": \"Diverted\", \"type\": \"string\"},{  \"name\": \"CarrierDelay\", \"type\": \"string\"},{  \"name\": \"WeatherDelay\", \"type\": \"string\"},{  \"name\": \"NASDelay\", \"type\": \"string\"},{  \"name\": \"SecurityDelay\", \"type\": \"string\"},{  \"name\": \"LateAircraftDelay\", \"type\": \"string\"}]}"
  }
}



